Criando TextBox e Labels Em Python Tkinter - 06
https://www.youtube.com/watch?v=i3vexAsQ1Wk&list=PL2Dw5PtrD32zzkQ1OQyN4gz3I_8G1MMHl&index=6

from tkinter import* 
import random
import time;
import datetime
root = Tk()
root.geometry("1350x750+0+0")
root.title("Sistema de vendas")
root.configure(background= 'grey')
#FRAMES PRIMÁRIOS
Tops = Frame (root, width=1350 , height=100 , bd= 14, relief= "raise")
Tops.pack(side = TOP)
framef1 = Frame (root, width=900 , height=650 , bd= 8 , relief= "raise")
framef1.pack(side=LEFT)
framef2 = Frame (root, width=440 , height=650 , bd= 8 , relief= "raise")
framef2.pack(side=RIGHT)
# FRAME SECUNDÁRIOS
frameft2 = Frame (framef2, width=440, height=650, bd=2, relief="raise")
frameft2.pack(side=TOP)
framefb2 = Frame (framef2, width=440, height=50, bd=2, relief="raise")
framefb2.pack(side=BOTTON)
framef1a = Frame (framef1a, width=900, height=330, bd=2, relief="raise")
framef1a.pack(side=TOP)
framef2a = Frame (framef1, width=900, height=320, bd=2, relief="raise")
framef2a.pack(side=BOTTON)
framef1aa = Frame (framef1a, width=450, height=330, bd=2, relief="raise")
framef2a.pack(side=LEFT)
framef1ab = Frame (framef1a, width=450, height=330, bd=2, relief="raise")
framefab.pack(side=RIGHT)
# TROCANDO A COR DE FUNDO DO FRAME DA ESQUERDA
framef1.configure(background 'grey')
# INSERINDO O RÓTULO DO CABECALHO COM O TÍTULO 
lblInfo=Label(Tops, font=('arial', 70, 'bold'), text="SISTEMA CAFETERIA", bd=8, width=23)
lblInfo=.grid(row=0, column=0)
#DECLARANDO AS PRIMEIRAS VARIÁVEIS 
var1 = IntVar()
var2 = IntVar()
var3 = IntVar()
var4 = IntVar()
var5 = IntVar()
var6 = IntVar()
var7 = IntVar()
var8 = IntVar()
var9 = IntVar()
var10 = IntVar()
var11 = IntVar()
var12 = IntVar()
var13 = IntVar()
var14 = IntVar()
var15 = IntVar()
var16 = IntVar()
var17 = IntVar()
var18 = IntVar()
# SETANDO AS VARIÁVEIS 
var1.set("0")
var2.set("0")
var3.set("0")
var4.set("0")
var5.set("0")
var6.set("0")
var7.set("0")
var8.set("0")
var9.set("0")
var10.set("0")
var11.set("0")
var12.set("0")
var13.set("0")
var14.set("0")
var15.set("0")
var16.set("0")
var17.set("0")
var18.set("0")
# CRIANDO OS RADIO BUTTONS PARA O CAFE
Latte= Checkbutton(framef1aa, text=”Latte \t", variable = var1, onvalue = 1, offvalue = 0, font='arial', 18, 'bold')).grid(row=0,sticky = W) 
Espresso= Checkbutton(framef1aa, text=”Espresso \t", variable = var2, onvalue = 1, offvalue = 0, font='arial', 18, 'bold')).grid(row=1,csticky = W) 
Iced_Latte= Checkbutton(framef1aa, text=”Iced_Latte \t", variable = var3, onvalue = 1, offvalue = 0, font='arial', 18, 'bold')).grid(row=2,sticky = W) 
Cafe_Gelado= Checkbutton(framef1aa, text=”Cafe_Gelado \t", variable = var4, onvalue = 1, offvalue = 0, font='arial', 18, 'bold')).grid(row=2,sticky = W) 
Cafe_Cortado= Checkbutton(framef1aa, text=”Cafe_Cortado  \t", variable = var5, onvalue = 1, offvalue = 0, font='arial', 18, 'bold')).grid(row=3,sticky = W) 
Cafe_Leite= Checkbutton(framef1aa, text=”Cafe_Leite \t", variable = var6, onvalue = 1, offvalue = 0, font='arial', 18, 'bold')).grid(row=4,sticky = W)
Cafe_Preto= Checkbutton(framef1aa, text=”Cafe_Preto \t", variable = var7, onvalue = 1, offvalue = 0, font='arial', 18, 'bold')).grid(row=5,sticky = W)
Cafe_Creme= Checkbutton(framef1aa, text=”Cafe_Creme \t", variable = var8, onvalue = 1, offvalue = 0, font='arial', 18, 'bold')).grid(row=6,sticky = W)   
Cappuccino= Checkbutton(framef1aa, text=”Cappuccino \t", variable = var9, onvalue = 1, offvalue = 0, font='arial', 18, 'bold')).grid(row=7,sticky = W)  
# CRIANDO OS RADIO BUTTONS PARA OS BOLOS
Latta = Checkbutton(framef1ab, text = "Latta \t", variable = var9, onvalue = 1, offvalue = 0, font=('arial', 18, 'bold')).grid(row=0,sticky = W)
Latta = Checkbutton(framef1ab, text = "Latta \t", variable = var10, onvalue = 1, offvalue = 0, font=('arial', 18, 'bold')).grid(row=0,sticky = W)
Latta = Checkbutton(framef1ab, text = "Latta \t", variable = var11, onvalue = 1, offvalue = 0, font=('arial', 18, 'bold')).grid(row=0,sticky = W)
Latta = Checkbutton(framef1ab, text = "Latta \t", variable = var12, onvalue = 1, offvalue = 0, font=('arial', 18, 'bold')).grid(row=0,sticky = W)
Latta = Checkbutton(framef1ab, text = "Latta \t", variable = var13, onvalue = 1, offvalue = 0, font=('arial', 18, 'bold')).grid(row=0,sticky = W)
Latta = Checkbutton(framef1ab, text = "Latta \t", variable = var14, onvalue = 1, offvalue = 0, font=('arial', 18, 'bold')).grid(row=0,sticky = W)
Latta = Checkbutton(framef1aa, text = "Latta \t", variable = var15, onvalue = 1, offvalue = 0, font=('arial', 18, 'bold')).grid(row=0,sticky = W)
Latta = Checkbutton(framef1ab, text = "Latta \t", variable = var16, onvalue = 1, offvalue = 0, font=('arial', 18, 'bold')).grid(row=0,sticky = W)
Latta = Checkbutton(framef1ab, text = "Latta \t", variable = var17, onvalue = 1, offvalue = 0, font=('arial', 18, 'bold')).grid(row=0,sticky = W)
Latta = Checkbutton(framef1ab, text = "Latta \t", variable = var18, onvalue = 1, offvalue = 0, font=('arial', 18, 'bold')).grid(row=0,sticky = W)
#CRIANDO OS CAMPOS DE TEXTO, CAIXA TEXTO.
txtLatte=Entry(frame1aa,font=('arial',16,'bold'),bd=1,width=6,justify='left', state=DISABLED)
txtLatte.grid(row=0,column=1)              
txtLatte=Entry(framef1aa, font=('arial', 16, 'bold'),bd=1,wdth=8,justify='left',state=DISABLED) 
txtLatte.grid(row=1,column=1)
txtLatte=Entry(framef1aa, font=('arial', 16, 'bold'),bd=1,wdth=8,justify='left',state=DISABLED) 
txtLatte.grid(row=2,column=1) 
txtLatte=Entry(framef1aa, font=('arial', 16, 'bold'),bd=1,wdth=8,justify='left',state=DISABLED) 
txtLatte.grid(row=3,column=1) 
txtLatte=Entry(framef1aa, font=('arial', 16, 'bold'),bd=1,wdth=8,justify='left',state=DISABLED) 
txtLatte.grid(row=4,column=1) 
txtLatte=Entry(framef1aa, font=('arial', 16, 'bold'),bd=1,wdth=8,justify='left',state=DISABLED) 
txtLatte.grid(row=5,column=1) 
txtLatte=Entry(framef1aa, font=('arial', 16, 'bold'),bd=1,wdth=8,justify='left',state=DISABLED) 
txtLatte.grid(row=6,column=1) 
txtLatte=Entry(framef1aa, font=('arial', 16, 'bold'),bd=1,wdth=8,justify='left',state=DISABLED) 
txtLatte.grid(row=7,column=1) 
txtLatte=Entry(framef1aa, font=('arial', 16, 'bold'),bd=1,wdth=8,justify='left',state=DISABLED) 
txtLatte.grid(row=8,column=1)     
root.mainloop()              


